// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7TaB5Uql9GAxN9md9g-AE1D9vMgWQ9aw',
    appId: '1:309063523457:web:1280c1b1a3f1d9cddf8180',
    messagingSenderId: '309063523457',
    projectId: 'shashop-46771',
    authDomain: 'shashop-46771.firebaseapp.com',
    storageBucket: 'shashop-46771.appspot.com',
    measurementId: 'G-FX2KH4QGKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbnX7TGXi-LgT_5n7A6PWlZt2ipTpJmrs',
    appId: '1:309063523457:android:f64b7caeb554ba91df8180',
    messagingSenderId: '309063523457',
    projectId: 'shashop-46771',
    storageBucket: 'shashop-46771.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYNUIWzltO1I3WgljXEoWYOnj1c-ut5Os',
    appId: '1:309063523457:ios:43ac09b909c4e90edf8180',
    messagingSenderId: '309063523457',
    projectId: 'shashop-46771',
    storageBucket: 'shashop-46771.appspot.com',
    iosBundleId: 'com.example.finallyshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYNUIWzltO1I3WgljXEoWYOnj1c-ut5Os',
    appId: '1:309063523457:ios:06092ca65fe43e06df8180',
    messagingSenderId: '309063523457',
    projectId: 'shashop-46771',
    storageBucket: 'shashop-46771.appspot.com',
    iosBundleId: 'com.example.finallyshop.RunnerTests',
  );
}
